version: "3.7"
services: 
  api-python-node:
    container_name: api-python-node
    image: api-python-node
    restart: always
    build: ./apiResearcher
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ~/data:/data/db
    ports:
      - "27017:27017"
    
        
  joker:
    container_name: joker
    image: joker
    restart: always
    build: .
    ports:
      - "1337:1337"
    links:
      - mongo
    depends_on:
      - mongo
      - api-python-node
    environment:
      WAIT_HOSTS: mongo:27017, api-python-node:3000
    

